// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zErrorResponse = z.object({
    message: z.string()
});

export const zLoginRequest = z.object({
    email: z.string(),
    password: z.string()
});

export const zLoginResponse = z.object({
    token: z.string()
});

export const zMessageResponse = z.object({
    message: z.string()
});

export const zProfileResponse = z.object({
    created_at: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    email: z.string(),
    id: z.string()
});

export const zRegisterRequest = z.object({
    email: z.string(),
    password: z.string()
});

export const zRegisterResponse = z.object({
    createdAt: z.optional(z.union([
        z.iso.datetime(),
        z.null()
    ])),
    email: z.string(),
    message: z.string(),
    userId: z.string()
});

export const zLoginHandlerData = z.object({
    body: zLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Login successful
 */
export const zLoginHandlerResponse = zLoginResponse;

export const zLogoutHandlerData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Logout successful
 */
export const zLogoutHandlerResponse = zMessageResponse;

export const zProfileHandlerData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Profile retrieved successfully
 */
export const zProfileHandlerResponse = zProfileResponse;

export const zRegisterHandlerData = z.object({
    body: zRegisterRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * User created successfully
 */
export const zRegisterHandlerResponse = zRegisterResponse;